[package]
name = "DynamicFrameAllocatorLib"
version = "0.1.0"
edition = "2021"

[lib]
name = "dynamic_frame_allocator_lib"
path = "src/lib.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spin = {workspace=true}