## @file
# File templates/pr-gate-build-job.yml
#
# template file used to build supported packages.
#
# Copyright (c) Microsoft Corporation.
# Copyright (c) 2020 - 2021, ARM Limited. All rights reserved.<BR>
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

parameters:
  - name: tool_chain_tag
    type: string
    default: ''
  - name: vm_image
    type: string
    default: ''
  - name: arch_list
    type: string
    default: ''
# Build step
jobs:

- job: Build_${{ parameters.tool_chain_tag }}
  variables:
    rust_target: 1.67 # Stable branch as of 10/21/2022
  #Use matrix to speed up the build process
  strategy:
    matrix:
      TARGET_Q35:
        Build.Pkgs: 'QemuQ35Pkg'
        Build.Targets: 'NO-TARGET'
  workspace:
    clean: all

  pool:
    vmImage: ${{ parameters.vm_image }}

  steps:
  - template: pr-gate-steps.yml
    parameters:
      tool_chain_tag: ${{ parameters.tool_chain_tag }}
      build_pkgs: $(Build.Pkgs)
      build_targets: $(Build.Targets)
      build_archs: ${{ parameters.arch_list }}
      extra_install_step:
      - task: RustInstaller@1
        inputs:
          rustVersion: ms-$(rust_target) 
          authenticationToken: $(RustInstallerToken)
        displayName: Install Microsoft Rust toolchain
      - task: Powershell@2 # In order to comply with msrustup
        inputs:
          targetType: 'inline'
          script: |
            New-Item -Path .cargo -ItemType Directory
            New-Item -Path .cargo/config.toml -ItemType File
            " 
            [source]
            crates-io = { replace-with = 'ms-crates-io' }
            ms-crates-io = { registry = '$(MsCratesIO)' }
            
            [net]
            git-fetch-with-cli = true" | Out-File -FilePath .cargo/config.toml -Append -encoding ASCII
            
        displayName: Overriding default crates-io with internal ms-crates-io
      - task: Powershell@2
        inputs:
          targetType: 'inline'
          script: cargo install --force cargo-make
        displayName: Install Cargo Make
