[package]
name = "dxe_rust"
version = "0.1.0"
authors = ["Hackathon Team"]
edition = "2018"

[dependencies]
linked_list_allocator = "0.9.0"
r-efi = "4.0.0"
spin = "0.5.2"
indoc = "1.0"
uart_16550 = "0.2.0"
volatile = "0.2.6"
x86_64 = "0.14.2"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]

[dependencies.uuid]
version = "1"
default-features = false

[dependencies.goblin]
version = "0.5.4"
default-features = false
features = ["pe32", "pe64"]

[dependencies.num-traits]
version = "0.2"
default-features = false

[dependencies.scroll]
version = "0.11"
default_features = false
features = ["derive"]