[package]
name = "DxeRust"
version = "0.1.0"
authors = ["Hackathon Team"]
edition = "2021"

[lib]
name = "dxe_rust"
path = "src/lib.rs"

[[bin]]
name = "DxeRust"
path = "src/main.rs"
test = false

[dependencies]
FvLib = {workspace=true}
DynamicFrameAllocatorLib = {workspace=true}
UefiRustAllocatorLib = {workspace=true}
UefiProtocolDbLib = {workspace=true}
UefiEventLib = {workspace=true}
UefiDevicePathLib = {workspace=true}
linked_list_allocator = {workspace=true}
r-efi = {workspace = true}
spin = {workspace = true}
indoc = {workspace = true}
uart_16550 = {workspace = true}
volatile = {workspace = true}
x86_64 = {workspace = true}
lazy_static = {workspace = true}
uuid = {workspace = true}
goblin = {workspace = true}
num-traits = {workspace = true}
scroll = {workspace = true}
crc32fast = {workspace = true}
r-pi = {workspace = true}
