[package]
name = "FvLib"
version = "0.1.0"
edition = "2021"

[lib]
name = "fv_lib"
path = "src/lib.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
r-efi = {workspace=true}
uuid = {workspace=true}
x86_64 = {workspace=true}
