[package]
name = "SerialPrintDxe"
version = "0.1.0"
edition = "2021"

[lib]
name = "serial_print_dxe"
path = "src/lib.rs"

[dependencies]
lazy_static = {workspace = true}
spin = {workspace=true}

[target.'cfg(target_arch = "x86_64")'.dependencies]
uart_16550 = {workspace = true}
x86_64 = {workspace = true}
