[package]
name = "UefiDepexLib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "uefi_depex_lib"
path = "src/lib.rs"

[dependencies]
r-efi = {workspace=true}
uuid = {workspace=true}
UefiProtocolDbLib = {workspace=true}
