## @file
# Azure Pipeline build file for a build using ubuntu and GCC5.
#
# NOTE: This file is automatically synchronized from Mu DevOps. Update the original file there
#       instead of the file in this repo.
#
# - Mu DevOps Repo: https://github.com/microsoft/mu_devops
# - File Sync Settings: https://github.com/microsoft/mu_devops/blob/main/.sync/Files.yml
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

resources:
  repositories:
    - repository: mu_devops
      type: github
      endpoint: microsoft
      name: microsoft/mu_devops
      ref: refs/tags/v2.3.1

variables:
- group: architectures-x86-64
- group: tool-chain-ubuntu-gcc
- group: 'UEFI Rust Tokens'

jobs:
- template: Jobs/PrGate.yml@mu_devops
  parameters:
    arch_list: $(arch_list)
    do_ci_build: true
    do_ci_setup: false
    do_non_ci_build: false
    do_non_ci_setup: true
    do_pr_eval: true
    extra_steps:
    - template: templates/git-config-auth.yml
    - script: sudo dnf --assumeyes install openssl-devel
      displayName: Install openssl
    - task: RustInstaller@1
      inputs:
        cratesIoFeedOverride: $(CratesIoFeedOverride)
        rustVersion: ms-$(RustVersion)
        toolchainFeed: $(RustToolChainFeed)
      displayName: Install Microsoft Rust toolchain
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'specific'
        project: 'MsUEFI'
        definition: 101356 # The pipeline definition
        targetPath: '$(CARGO_HOME)\bin\'
        itemPattern: '**/cargo-make'
        artifactName: 'Binaries'
      displayName: Download Cargo Make
    - script: sudo chmod +x $(CARGO_HOME)/bin/cargo-make
    packages: QemuQ35Pkg
    target_list: NO-TARGET
    tool_chain_tag: $(tool_chain_tag)
    vm_image: ubuntu-latest
    container_build: true
    linux_container_image: ghcr.io/tianocore/containers/fedora-37-build:f1c7a20
    linux_container_options: --security-opt seccomp=unconfined

