# Specifies labels to apply to pull requests in Patina repositories based on regular expressions.
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
#
# For more information, see:
# https://github.com/srvaroa/labeler

# Maintenance: Keep labels organized in ascending alphabetical order - easier to scan, identify duplicates, etc.
version: 1
issues: False

labels:
  - label: type:backport
    type: "pull_request"
    body: '\s*\[\s*(x|X){1}\s*\]\s*Backport to release branch\?'

  - label: type:backport
    type: "pull_request"
    authors: ["mu-automation[bot]"]
    branch : "repo-sync/mu_devops/default"  
    base-branch: "dev/20[0-9]{4}"

  - label: type:backport
    type: "pull_request"
    authors: ["dependabot[bot]"]
    branch : "dependabot/*"
    base-branch: "dev/20[0-9]{4}"

  - label: impact:breaking-change
    type: "pull_request"
    body: '\s*\[\s*(x|X){1}\s*\]\s*Breaking\s*change\?'

  - label: type:documentation
    type: "pull_request"
    body: '\s*\[\s*(x|X){1}\s*\]\s*Includes\s*documentation\?'

  - label: impact:non-functional
    type: "pull_request"
    body: '\s*\[\s*\]\s*Impacts\s*functionality\?'

  - label: impact:security
    type: "pull_request"
    body: '\s*\[\s*(x|X){1}\s*\]\s*Impacts\s*security\?'

  - label: impact:testing
    type: "pull_request"
    body: '\[\s*(x|X){1}\s*\]\s*Includes\s*tests\?'
